steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - intania92-runner-bot
  - --no-gen2
  - --region=asia-southeast1
  - --trigger-http
  - --source=.
  - --entry-point=main
  - --memory=512MB
  - --runtime=python311
